### ISSUE TITLE
Where is the Src directory you mention?

### ISSUE THREAD

**Issue by mrmowgli** [Zinggi/UnrealScriptIDE#26]
I'm on OSX, and I am assuming you are talking about the Unreal sources from GIT not my project sources.  The doc mentions some glorious folder named UDK*, however I have no such folder and there isn't a folder structure like that on the Mac as far as I can tell.

Where is this magical folder????????

**Comment by Zinggi** [comment]
I think you're confusing something.
This plugin was developed for UDK, that is Unreal Engine **3**.
You are most likely using Unreal Engine **4** and this plugin wouldn't be helpful for that at all.

**Comment by mrmowgli** [comment]
Understood.  Any plans for adding UE4 support?

**Comment by Zinggi** [comment]
No, I don't have any plans for that, sorry.

Besides, aren't there any good c++ plugins out there?
Since UE4 doesn't use it's own scripting language anymore, I don't see why a general c++ plugin wouldn't suffice.

**Comment by rokit** [comment]
The officially supported IDE for UE4 v10+ is Visual Studio 15, paid or free version.  The free version is called Community edition.  If you create a C++ project, the engine will give you a link to download it if it is not already installed.

https://docs.unrealengine.com/latest/INT/Programming/Development/VisualStudioSetup/index.html

**Comment by rokit** [comment]
Sorry, just realized you're using OSX.  I believe you can compile using xcode.  Since I don't have OSX I can't help you there, but you might want to check UE4's answerhub.

https://answers.unrealengine.com/search.html?q=xcode&c=13&type=question+OR+idea&lang=en&sort=relevance&author=&productVer=default

**Comment by mrmowgli** [comment]
No worries, I just liked the way your plugin was set up and I prefer
working in Sublime, especially if I could take advantage of the
autocomplete and snippets work you did, edpecially since I am also using
Linux.
