### ISSUE TITLE
How to disable auto-completion with 'tab'?

### ISSUE THREAD

**Issue by arslancharyev31** [Zinggi/UnrealScriptIDE#27]
Good day.  I'm having issues with tab key, which frequently autocompletes a statement, instead of inserting a `\t` character. I've tried disabling it in `UnrealScriptIDE.sublime-settings` via `"auto_complete_commit_on_tab": false` and `"auto_complete_with_fields": false` options, but without any luck. 
I've also tried changing user keymap to
```
[
	{
		"keys": ["tab"],
		"command": "", 
		...
	}
]
```
But that didn't help as well. Any suggestions?

**Comment by Zinggi** [comment]
Try pressing `shift+tab`, this should insert a literal tab.

This isn't an issue with this plugin, that's just how sublimes autocomplete system works. 
Hope that helps 😃

**Comment by arslancharyev31** [comment]
Indeed it does. Thx a lot.

**Comment by Zinggi** [comment]
Glad I could help!
